feature-branch
iamfarhatsharefi/product-landing-page pull request #1
Opened 2024-05-28 15:23 UTC by iamfarhatsharefi

This PR introduces GUCCI brand, visually stunning product landing page designed to captivate and convert visitors. development branch is the default branch and my project is already pushed to my feature branch. 
with respect Feedback on the design and functionality is highly appreciated.

2024-05-28 23:33 UTC, ahzamir requested changes
### Hi @iamfarhatsharefi 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although your code passes the freecodecamp checks, but still you need to work on the project design and your README.md file inorder to get the final approval.
- [OPTIONAL] - You added a simple design to your code, add some more design and make it look more amazing for users.
- Your README.md file has some issues, check the inline comments below for more details

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
👍 A simple Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Product Landing Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
❌Your project has a professional READMe.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-28 23:33 UTC, ahzamir commented on README.md
> +https://www.linkedin.com/in/farhat-sharefi-13a101309?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app
- Try to add a screenshot here as a Demo of your project.

2024-05-28 23:33 UTC, ahzamir commented on README.md
> +
Instead of this just give user a hint and a command for cloning your project and opening it on browser.

2024-05-28 23:33 UTC, ahzamir commented on README.md
> +
- Add some hint for contribution or remove this part if you don't want to add it.

2024-05-28 23:33 UTC, ahzamir commented on README.md
> +Thanks again for your interest in contributing!
- Remove the License if you don't have on your project.

2024-05-28 23:33 UTC, ahzamir commented on README.md
> +- LinkedIn:https://www.linkedin.com/in/farhat-sharefi-13a101309?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app
- This is a link to a post on LinkedIn instead share your LinkedIn profile here.

2024-05-29 12:14 UTC, iamfarhatsharefi commented
@ahzamir sir again as your feedback was adding some styles and adding demo to my readme i do all of them.

2024-06-01 11:20 UTC, ahzamir approved these changes
### Hi @iamfarhatsharefi 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

✔️ A simple Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-02 10:21 UTC, merged